# Use official Node.js version 20.18.0 image as the base
FROM node:20.18.0

# Set working directory
WORKDIR /app/frontend

# Expose the frontend port
EXPOSE 3000

# Copy package.json and package-lock.json, then install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the frontend code
COPY . .

# Build the React app for production
RUN npm run build

# Use the locally installed 'serve' to serve the built app
CMD ["npm", "run", "serve"]
