# Use an official Node.js image as the base
FROM node:23

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json, if present
COPY package.json ./
COPY .env .env

# Install dependencies
RUN npm install

# Copy the remaining backend code
COPY . .

# Expose the backend port
EXPOSE 3000

# Command to start the backend server
CMD ["node", "index.js"]